In [1]:
#import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#load the dataset

df = pd.read_excel('C:/Users/ADMIN/Documents/VEES_Bulletin_Hackathon/Datasets/combined_reports.xlsx')

In [3]:
# checking the first 5 rows of the dataset
df.head(5)

,Source Form Version,Submitter UUID,Submitter Username,Submitter Name,Submitter Organization,Submitter Role,Id,Date of Report,Date of Start of Outbreak/Event,Date Event Reported,...,Number Slaughtered,Number Destroyed,Number Vaccinated,Disease Control Method,Other Control Method,Location,Location.1,Longitude,Latitude,Number Sick
0,v15 ND1 Form,9a6318e3-df44-4bd0-cf48-55bb750a9f1b,dkinoti,Daniel kinoti Rutere,NaN,Government Veterinarian,4f35496e-deae-4609-bf58-b32ceb78b779,2020-02-19,2020-02-19,2020-02-19,...,0,0,0,[Treatment],NaN,NaN,NaN,NaN,NaN,NaN
1,v15 ND1 Form,41326f3f-bdb9-4297-d71f-f964525dbf7e,A.Siraj,Abukar Siraj,NaN,Sub-county Officer,8eb35a65-7436-4637-9601-3bd947b7bb7c,2020-02-22,2020-02-09,2020-02-22,...,0,0,0,[Treatment],NaN,NaN,NaN,NaN,NaN,NaN
2,v15 ND1 Form,41561c2c-cd22-40b0-af7e-cc3a3e8fd7f7,mirungu,Michael Irungu,NaN,Government Animal Health Assistant,4292b90c-1268-4dd6-a60f-fd9cded2a722,2020-02-20,2020-02-20,2020-02-20,...,0,0,0,[Treatment],NaN,NaN,NaN,NaN,NaN,NaN
3,v15 ND1 Form,e7ca22f0-7f2b-4724-bebc-b53fddb71a34,livingstone,Livingstone Koskei,NaN,Government Animal Health Assistant,5feff171-a62a-441f-a0d5-810dbd7b9da1,2020-03-02,2020-03-01,2020-03-02,...,0,0,280,"[Treatment, Quarantine, Vaccination]",NaN,NaN,NaN,NaN,NaN,NaN
4,v15 ND1 Form,fec9de74-27af-46ce-c207-734ac3fe8f17,Fredrick mbaru,Fredrick mbaru,NaN,Government Animal Health Assistant,108cbee5-11e2-4a9b-9172-b9bb5bcfae96,2020-02-24,2020-02-23,2020-02-23,...,0,0,0,[Treatment],NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#checking the shape of the dataset and columns

df.shape
df.columns

Index(['Source Form Version', 'Submitter UUID', 'Submitter Username',
       'Submitter Name', 'Submitter Organization', 'Submitter Role', 'Id',
       'Date of Report', 'Date of Start of Outbreak/Event',
       'Date Event Reported', 'County', 'Sub-County', 'Ward', 'Locality',
       'Species Affected', 'Other Species', 'Production System', 'Abortion',
       'Number Affected', 'Sudden Death', 'Number Affected.1', 'Death',
       'Number Affected.2', 'Hemorrhagic Signs', 'Number Affected.3',
       'Neurologic signs', 'Number Affected.4', 'Animal Bites',
       'Number Affected.5', 'Respiratory Signs', 'Number Affected.6',
       'Oral/Foot Lesions', 'Number Affected.7', 'Cutaneous/Skin Lesions',
       'Number Affected.8', 'Gastrointestinal tract syndromes',
       'Number Affected.9', 'Other Syndromes', 'Number Affected.10',
       'Number at Risk', 'Number Sick / Bitten', 'Number Dead',
       'Disease/Condition', 'Other Disease', 'Nature of Diagnosis',
       'Test Used', 'Number of Humans Affected (If zoonosis)',
       'Number Slaughtered', 'Number Destroyed', 'Number Vaccinated',
       'Disease Control Method', 'Other Control Method', 'Location',
       'Location.1', 'Longitude', 'Latitude', 'Number Sick'],
      dtype='str')

In [5]:
# Checking the data types of the columns
df.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 65158 entries, 0 to 65157
Data columns (total 57 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Source Form Version                      65158 non-null  str
 1   Submitter UUID                           65158 non-null  str
 2   Submitter Username                       65158 non-null  str
 3   Submitter Name                           65158 non-null  str
 4   Submitter Organization                   61153 non-null  str
 5   Submitter Role                           65139 non-null  str
 6   Id                                       65158 non-null  str
 7   Date of Report                           65158 non-null  str
 8   Date of Start of Outbreak/Event          65158 non-null  str
 9   Date Event Reported                      431 non-null    str
 10  County                                   65158 non-null  str
 11  Sub-County                               65158 non-null  str
 12  Ward                                     65158 non-null  str
 13  Locality                                 65158 non-null  str
 14  Species Affected                         65158 non-null  str
 15  Other Species                            134 non-null    str
 16  Production System                        60159 non-null  str
 17  Abortion                                 65158 non-null  str
 18  Number Affected                          4875 non-null   float64
 19  Sudden Death                             65158 non-null  str
 20  Number Affected.1                        3092 non-null   float64
 21  Death                                    11265 non-null  str
 22  Number Affected.2                        5777 non-null   float64
 23  Hemorrhagic Signs                        65158 non-null  str
 24  Number Affected.3                        4330 non-null   float64
 25  Neurologic signs                         65158 non-null  str
 26  Number Affected.4                        2702 non-null   float64
 27  Animal Bites                             65158 non-null  str
 28  Number Affected.5                        18738 non-null  float64
 29  Respiratory Signs                        65158 non-null  str
 30  Number Affected.6                        8947 non-null   float64
 31  Oral/Foot Lesions                        65158 non-null  str
 32  Number Affected.7                        9891 non-null   float64
 33  Cutaneous/Skin Lesions                   65158 non-null  str
 34  Number Affected.8                        15564 non-null  float64
 35  Gastrointestinal tract syndromes         65158 non-null  str
 36  Number Affected.9                        13896 non-null  float64
 37  Other Syndromes                          65158 non-null  str
 38  Number Affected.10                       2222 non-null   float64
 39  Number at Risk                           65158 non-null  int64
 40  Number Sick / Bitten                     11265 non-null  float64
 41  Number Dead                              65158 non-null  int64
 42  Disease/Condition                        65158 non-null  str
 43  Other Disease                            12882 non-null  str
 44  Nature of Diagnosis                      65072 non-null  str
 45  Test Used                                539 non-null    str
 46  Number of Humans Affected (If zoonosis)  54199 non-null  float64
 47  Number Slaughtered                       65158 non-null  int64
 48  Number Destroyed                         65158 non-null  int64
 49  Number Vaccinated                        65158 non-null  int64
 50  Disease Control Method                   65158 non-null  str
 51  Other Control Method                     4592 non-null   str
 52  Location                                 58337 non-null  float64
 53  Location.1                               58351 non-null  float64
 54  Longitude                                58351 non-null  float64
 55  Latitude                                 58337 non-null  float64
 56  Number Sick                              53893 non-null  float64
dtypes: float64(18), int64(5), str(34)
memory usage: 28.3 MB

In [6]:
#adjusting the right data types for the columns

# 1. Dates
date_cols = [
    "Date of Report",
    "Date of Start of Outbreak/Event",
    "Date Event Reported"
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")


# 2. Numeric/count variables
numeric_cols = [
    "Number Affected",
    "Number Affected.1",
    "Number Affected.2",
    "Number Affected.3",
    "Number Affected.4",
    "Number Affected.5",
    "Number Affected.6",
    "Number Affected.7",
    "Number Affected.8",
    "Number Affected.9",
    "Number Affected.10",
    "Number at Risk",
    "Number Sick / Bitten",
    "Number Dead",
    "Number of Humans Affected (If zoonosis)",
    "Number Slaughtered",
    "Number Destroyed",
    "Number Vaccinated",
    "Number Sick",
    "Longitude",
    "Latitude"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")


# 3. Categorical variables
categorical_cols = [
    "Source Form Version",
    "Submitter Organization",
    "Submitter Role",
    "County",
    "Sub-County",
    "Ward",
    "Locality",
    "Species Affected",
    "Other Species",
    "Production System",
    "Abortion",
    "Sudden Death",
    "Death",
    "Hemorrhagic Signs",
    "Neurologic signs",
    "Animal Bites",
    "Respiratory Signs",
    "Oral/Foot Lesions",
    "Cutaneous/Skin Lesions",
    "Gastrointestinal tract syndromes",
    "Other Syndromes",
    "Disease/Condition",
    "Other Disease",
    "Nature of Diagnosis",
    "Test Used",
    "Disease Control Method",
    "Other Control Method"
]

for col in categorical_cols:
    df[col] = df[col].astype("category")


# 4. Identifiers
id_cols = [
    "Submitter UUID",
    "Submitter Username",
    "Submitter Name",
    "Id"
]

for col in id_cols:
    df[col] = df[col].astype("string")

In [7]:
#checking the null values in the dataset
null_values = df.isnull().sum()

null_summary = pd.DataFrame({
    "Null Count": null_values,
    "Null Percentage": (null_values / len(df) * 100).round(2)
})

null_summary.sort_values(by="Null Percentage", ascending=False)

                                         Null Count  Null Percentage
Other Species                                 65024            99.79
Date Event Reported                           64727            99.34
Test Used                                     64619            99.17
Number Affected.10                            62936            96.59
Number Affected.4                             62456            95.85
Number Affected.1                             62066            95.25
Number Affected.3                             60828            93.35
Other Control Method                          60566            92.95
Number Affected                               60283            92.52
Number Affected.2                             59381            91.13
Number Affected.6                             56211            86.27
Number Affected.7                             55267            84.82
Number Sick / Bitten                          53893            82.71
Death                                         53893            82.71
Other Disease                                 52276            80.23
Number Affected.9                             51262            78.67
Number Affected.8                             49594            76.11
Number Affected.5                             46420            71.24
Number Sick                                   11265            17.29
Number of Humans Affected (If zoonosis)       10959            16.82
Latitude                                       6821            10.47
Location                                       6821            10.47
Longitude                                      6807            10.45
Location.1                                     6807            10.45
Production System                              4999             7.67
Submitter Organization                         4005             6.15
Nature of Diagnosis                              86             0.13
Submitter Role                                   19             0.03
Abortion                                          0             0.00
Ward                                              0             0.00
Sub-County                                        0             0.00
Species Affected                                  0             0.00
County                                            0             0.00
Submitter Name                                    0             0.00
Source Form Version                               0             0.00
Submitter Username                                0             0.00
Submitter UUID                                    0             0.00
Date of Report                                    0             0.00
Id                                                0             0.00
Date of Start of Outbreak/Event                   0             0.00
Locality                                          0             0.00
Hemorrhagic Signs                                 0             0.00
Sudden Death                                      0             0.00
Cutaneous/Skin Lesions                            0             0.00
Gastrointestinal tract syndromes                  0             0.00
Animal Bites                                      0             0.00
Neurologic signs                                  0             0.00
Respiratory Signs                                 0             0.00
Oral/Foot Lesions                                 0             0.00
Number at Risk                                    0             0.00
Other Syndromes                                   0             0.00
Disease/Condition                                 0             0.00
Number Dead                                       0             0.00
Number Destroyed                                  0             0.00
Number Slaughtered                                0             0.00
Number Vaccinated                                 0             0.00
Disease Control Method                            0             0.00

In [8]:
#columns to drop from the dataset

cols_to_drop = [
    "Date Event Reported",
    "Test Used",
    "Number Affected.10",
    "Number Affected.4",
    "Number Affected.1",
    "Number Affected.3",
    "Number Affected",
    "Number Affected.2",
    "Number Affected.6",
    "Number Affected.7",
    "Number Affected.8",
    "Number Affected.9",
    "Number Affected.5",
    "Death",
    "Location",
    "Location.1",
    "Submitter UUID",
    "Submitter Username",
    "Submitter Name",
    "Id",
    "Source Form Version",
    "Submitter Organization",
    "Submitter Role",
    "Hemorrhagic Signs",
    "Neurologic signs",
    "Animal Bites",
    "Respiratory Signs",
    "Oral/Foot Lesions",
    "Cutaneous/Skin Lesions",
    "Gastrointestinal tract syndromes",
    "Other Syndromes",
    "Number Destroyed",
    "Number Vaccinated",
    "Date of Start of Outbreak/Event",
    "Production System",
    "Number Slaughtered",
    "Abortion",
    "Sudden Death"
]

df1 = df.drop(columns=cols_to_drop)

print(f"\nRemaining dataset shape: {df1.shape}")

Remaining dataset shape: (65158, 19)

In [9]:
#fill 0 in the numericals variables

num_cols = ["Number Sick / Bitten", "Number Sick", "Number of Humans Affected (If zoonosis)"]
df1[num_cols] = df1[num_cols].fillna(0)

In [10]:
#filling the nulls for coordinates

# Fill hierarchy: Ward -> Sub-County -> County
for group_col in ['Ward', 'Sub-County', 'County']:
    df1['Latitude'] = df1['Latitude'].fillna(
        df1.groupby(group_col)['Latitude'].transform('mean')
    )
    df1['Longitude'] = df1['Longitude'].fillna(
        df1.groupby(group_col)['Longitude'].transform('mean')
    )

# Check how many are still missing after all three levels
print(df1[['Latitude', 'Longitude']].isna().sum())

Latitude     0
Longitude    0
dtype: int64

In [11]:
#fill the nulls in nature of diagnosis as "unkown"

df1['Nature of Diagnosis'] = df1['Nature of Diagnosis'].cat.add_categories('Unknown')
df1['Nature of Diagnosis'] = df1['Nature of Diagnosis'].fillna('Unknown')

In [12]:
df1.isnull().sum().sort_values()

Date of Report                                 0
County                                         0
Sub-County                                     0
Ward                                           0
Locality                                       0
Species Affected                               0
Number at Risk                                 0
Number Sick / Bitten                           0
Disease Control Method                         0
Number Dead                                    0
Disease/Condition                              0
Nature of Diagnosis                            0
Number of Humans Affected (If zoonosis)        0
Number Sick                                    0
Latitude                                       0
Longitude                                      0
Other Disease                              52276
Other Control Method                       60566
Other Species                              65024
dtype: int64

In [13]:
#mapping the "other" columns to the main variables

mapping = {
    'Disease/Condition': 'Other Disease',
    'Disease Control Method': 'Other Control Method',
    'Species Affected': 'Other Species'
}

for main_col, other_col in mapping.items():
    # drop categorical dtype temporarily so assignment isn't restricted
    df1[main_col] = df1[main_col].astype(object)
    df1[other_col] = df1[other_col].astype(object)

    mask = df1[main_col].isna() | (df1[main_col] == 'Other')
    df1.loc[mask, main_col] = df1.loc[mask, other_col]

In [14]:
# dropping the other columns

df2 = df1.drop(columns=['Other Disease', 'Other Control Method', 'Other Species'])

In [15]:
#fill unkown values to  Disease/condition
if isinstance(df1['Disease/Condition'].dtype, pd.CategoricalDtype):
    df2['Disease/Condition'] = df2['Disease/Condition'].cat.add_categories('Unknown')

df2['Disease/Condition'] = df2['Disease/Condition'].fillna('Unknown')

In [16]:
df2.isnull().sum().sort_values

<bound method Series.sort_values of Date of Report                             0
County                                     0
Sub-County                                 0
Ward                                       0
Locality                                   0
Species Affected                           0
Number at Risk                             0
Number Sick / Bitten                       0
Number Dead                                0
Disease/Condition                          0
Nature of Diagnosis                        0
Number of Humans Affected (If zoonosis)    0
Disease Control Method                     0
Longitude                                  0
Latitude                                   0
Number Sick                                0
dtype: int64>

In [18]:
df2.to_csv("../Cleaned Data/Kabs_cleaned.csv", index=False)